from __future__ import annotations

import shutil
import tempfile
from datetime import UTC, datetime
from pathlib import Path

from .capture.scoop import ScoopBackend
from .identifiers import IdentifierStore, validate_identifier
from .images import validate_png
from .metadata import build_metadata, save_json, validate_metadata
from .packaging import write_manifest, write_validation_report, zip_package
from .urls import normalize_instagram_url
from .validation import validate_package
from .wacz import validate_wacz


def archive(
    url: str,
    output_dir: Path,
    timeout=None,
    identifier=None,
) -> dict:
    """Capture an Instagram URL and produce a validated preservation package.

    Orchestrates capture (Scoop/Chromium), metadata generation, WACZ/screenshot
    validation, and ZIP packaging. Returns a dict with the allocated
    `identifier`, resulting `zip_path`, and `final_status` ("complete",
    "partial", or "failed").
    """
    normalized = normalize_instagram_url(url)
    db = IdentifierStore(Path("workspace/postpreserve.db"))
    if identifier:
        if not validate_identifier(identifier):
            raise ValueError("Invalid identifier format")
    else:
        identifier = db.allocate("PP", "IG")

    output_dir.mkdir(parents=True, exist_ok=True)
    temp = tempfile.TemporaryDirectory(prefix=f".{identifier}.", dir=output_dir)
    staging = Path(temp.name)
    workdir = staging / "work"
    package_dir = staging / "package"
    workdir.mkdir()
    package_dir.mkdir()
    backend = ScoopBackend()
    try:
        artifacts = backend.capture(
            url=normalized.normalized,
            workdir=workdir,
            timeout_seconds=timeout or 90,
            headed=False,
            browser_profile=None,
        )
    except Exception as exc:
        temp.cleanup()
        return {"identifier": identifier, "final_status": "failed", "errors": [str(exc)]}

    post_type = "reel" if "/reel" in normalized.normalized else "post"
    page_info = artifacts.source_metadata.get("pageInfo", {})
    media_count = artifacts.source_metadata.get("media_count_captured")
    metadata = build_metadata(
        identifier=identifier,
        platform="instagram",
        platform_code="IG",
        original_url=url,
        normalized_url=normalized.normalized,
        source_identifier=normalized.source_identifier,
        shortcode=normalized.shortcode,
        post_type=post_type,
        page_title=page_info.get("title"),
        capture_status="complete",
        capture_tool=backend.name,
        capture_tool_version="0.6.58",
        browser="Chromium",
        browser_version=None,
        caption=page_info.get("description"),
        media_count_detected=media_count,
        media_count_captured=media_count,
    )
    save_json(package_dir / "metadata/metadata.json", metadata)
    save_json(package_dir / "metadata/source-metadata.json", artifacts.source_metadata)
    readme = package_dir / "documentation/README.txt"
    readme.parent.mkdir(parents=True, exist_ok=True)
    readme.write_text(
        "PostPreserve package generated by the archive workflow.\n"
        f"Identifier: {identifier}\n"
        f"Original URL: {url}\n",
        encoding="utf-8",
    )
    target_wacz = package_dir / "data/web/post.wacz"
    target_wacz.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(artifacts.wacz_path, target_wacz)
    if artifacts.screenshot_path and artifacts.screenshot_path.exists():
        target = package_dir / "data/representations/screenshot.png"
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(artifacts.screenshot_path, target)
    wacz_result = validate_wacz(target_wacz, normalized.normalized)
    screenshot_errors = (
        validate_png(package_dir / "data/representations/screenshot.png")
        if artifacts.screenshot_path
        else ["Screenshot is missing"]
    )
    screenshot_valid = not screenshot_errors
    metadata_errors = validate_metadata(metadata, Path("schemas/metadata.schema.json"))
    capture_report = {
        "identifier": identifier,
        "validation": {
            "wacz": wacz_result.valid,
            "metadata": not metadata_errors,
            "screenshot": screenshot_valid,
        },
        "errors": metadata_errors + wacz_result.errors + screenshot_errors,
        "warnings": wacz_result.warnings,
        "final_status": (
            "complete"
            if not metadata_errors and wacz_result.valid and screenshot_valid
            else "partial"
        ),
        "capture_date": datetime.now(UTC).isoformat(),
    }
    report_path = package_dir / "metadata/capture-report.json"
    save_json(report_path, capture_report)
    write_manifest(package_dir)
    write_validation_report(package_dir, {})
    package_validation = validate_package(package_dir)
    write_validation_report(package_dir, package_validation)
    zip_path = output_dir / f"{identifier}.zip"
    zip_package(package_dir, zip_path)
    temp.cleanup()
    return {
        "identifier": identifier,
        "zip_path": str(zip_path),
        "final_status": package_validation["final_status"],
        "package_validation": package_validation,
    }


def inspect_wacz(path: Path) -> dict:
    """Validate a standalone WACZ file and summarize its contents for the CLI."""
    result = validate_wacz(path)
    return {
        "valid": result.valid,
        "errors": result.errors,
        "warnings": result.warnings,
        "files": result.files,
        "urls": result.urls,
        "size": path.stat().st_size if path.exists() else 0,
    }
