from __future__ import annotations

import shutil
from datetime import UTC, datetime
from pathlib import Path

from .capture.browsertrix import BrowsertrixBackend
from .config import load_default_config
from .identifiers import IdentifierStore, validate_identifier
from .metadata import build_metadata, save_json, validate_metadata
from .packaging import assemble_package, write_manifest, write_validation_report, zip_package
from .platforms.instagram import InstagramAdapter
from .urls import normalize_instagram_url
from .validation import validate_package
from .wacz import validate_wacz


def archive(
    url: str,
    output_dir: Path,
    browser_profile=None,
    timeout=None,
    identifier=None,
    headed: bool = False,
    keep_workdir: bool = False,
    container_runtime=None,
) -> dict:
    config = load_default_config()
    normalized = normalize_instagram_url(url)
    platform = InstagramAdapter().identify(url)
    db = IdentifierStore(Path("workspace/postpreserve.db"))
    if identifier:
        if not validate_identifier(identifier):
            raise ValueError("Invalid identifier format")
    else:
        identifier = db.allocate(config.prefix, platform.platform_code)
    root = output_dir / identifier
    workdir = root / "work"
    root.mkdir(parents=True, exist_ok=True)
    workdir.mkdir(parents=True, exist_ok=True)
    backend = BrowsertrixBackend()
    try:
        artifacts = backend.capture(
            url=normalized.normalized,
            workdir=workdir,
            timeout_seconds=timeout or config.capture.timeout_seconds,
            headed=headed,
            browser_profile=browser_profile,
        )
    except Exception as exc:
        report = {"identifier": identifier, "final_status": "failed", "errors": [str(exc)]}
        save_json(root / "metadata/capture-report.json", report)
        return report
    metadata = build_metadata(
        identifier=identifier,
        platform="instagram",
        platform_code="IG",
        original_url=url,
        normalized_url=normalized.normalized,
        source_identifier=normalized.source_identifier,
        shortcode=normalized.shortcode,
        post_type=platform.post_type,
        page_title=None,
        capture_status="complete",
        capture_tool="browsertrix",
        capture_tool_version=None,
        browser=None,
        browser_version=None,
    )
    save_json(root / "metadata/metadata.json", metadata)
    save_json(root / "metadata/source-metadata.json", artifacts.source_metadata)
    readme = root / "documentation/README.txt"
    readme.parent.mkdir(parents=True, exist_ok=True)
    readme.write_text(
        "PostPreserve package generated by the archive workflow.\n"
        f"Identifier: {identifier}\n"
        f"Original URL: {url}\n",
        encoding="utf-8",
    )
    if artifacts.wacz_path.exists():
        target = root / "data/web/post.wacz"
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(artifacts.wacz_path, target)
    if artifacts.screenshot_path and artifacts.screenshot_path.exists():
        target = root / "data/representations/screenshot.png"
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(artifacts.screenshot_path, target)
    wacz_result = validate_wacz(artifacts.wacz_path, normalized.normalized)
    screenshot_valid = bool(
        artifacts.screenshot_path
        and artifacts.screenshot_path.exists()
        and artifacts.screenshot_path.stat().st_size > 0
    )
    metadata_errors = validate_metadata(metadata, Path("schemas/metadata.schema.json"))
    capture_report = {
        "identifier": identifier,
        "validation": {
            "wacz": wacz_result.valid,
            "metadata": not metadata_errors,
            "screenshot": screenshot_valid,
        },
        "errors": metadata_errors + wacz_result.errors,
        "warnings": wacz_result.warnings,
        "final_status": (
            "complete"
            if not metadata_errors and wacz_result.valid and screenshot_valid
            else "partial"
        ),
        "capture_date": datetime.now(UTC).isoformat(),
    }
    report_path = root / "metadata/capture-report.json"
    save_json(report_path, capture_report)
    package_dir = root / "package"
    assemble_package(root, package_dir)
    write_manifest(package_dir)
    package_validation = validate_package(package_dir)
    write_validation_report(package_dir, package_validation)
    zip_path = output_dir / f"{identifier}.zip"
    zip_package(package_dir, zip_path)
    if not keep_workdir:
        shutil.rmtree(workdir, ignore_errors=True)
    return {
        "identifier": identifier,
        "zip_path": str(zip_path),
        "package_validation": package_validation,
    }


def inspect_wacz(path: Path) -> dict:
    result = validate_wacz(path)
    return {
        "valid": result.valid,
        "errors": result.errors,
        "warnings": result.warnings,
        "files": result.files,
        "urls": result.urls,
        "size": path.stat().st_size if path.exists() else 0,
    }
